version: 2

sources:

  - name: uwinnipeg
    description: "Class test data"
    database: KRISHNAKUMAR_DAM
    schema: class_test
    tables:
      - name: CUSTOMERS
        description: "this is the customer table info"
      - name: ORDERS
        description: "this is orders table info"
      - name: PRODUCTS
        description: "This is a product table info"